export enum ActionType {
    INIT_WEB3_PENDING = "INIT_WEB3_PENDING",
    INIT_WEB3_SUCCESS = "INIT_WEB3_SUCCESS",
    INIT_WEB3_FAIL = "INIT_WEB3_FAIL",
    GET_ACCOUNT_PENDING = "GET_ACCOUNT_PENDING",
    GET_ACCOUNT_SUCCESS = "GET_ACCOUNT_SUCCESS",
    GET_ACCOUNT_FAIL = "GET_ACCOUNT_FAIL",
    SET_HAO_CONTRACT = "SET_HAO_CONTRACT", //TODO: Move to contract reducer
    SET_HAO_BALANCE = "SET_HAO_BALANCE",
    SET_NETWORK_ID = "SET_NETWORK_ID",
    SET_POOL_INFO = "SET_POOL_INFO",
    STAKE_SUCCESS = "STAKE_SUCCESS",
    OPEN_STAKING = "OPEN_STAKING",
    CLOSE_STAKING = "CLOSE_STAKING",
    OPEN_UNSTAKING = "OPEN_UNSTAKING",
    CLOSE_UNSTAKING = "CLOSE_UNSTAKING"
  }
  
  export type Action = {
    type: ActionType,
    payload?: any
  }
  